"""add_raw_query_typed_tables

Revision ID: 2c081eeee9d3
Revises: b4e2f1c9d7a0
Create Date: 2026-03-23 21:09:05.523974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c081eeee9d3'
down_revision: Union[str, Sequence[str], None] = 'b4e2f1c9d7a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Convenience alias — AutoString() is just unbounded VARCHAR in SQLite
_S = sa.String


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_query_blocker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_hash', _S(), nullable=False),
    sa.Column('environment', _S(), nullable=False),
    sa.Column('month_year', _S(), nullable=True),
    sa.Column('currentdbname', _S(), nullable=True),
    sa.Column('victims', _S(), nullable=True),
    sa.Column('resources', _S(), nullable=True),
    sa.Column('lock_modes', _S(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('latest', _S(), nullable=True),
    sa.Column('earliest', _S(), nullable=True),
    sa.Column('all_query', _S(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_query_blocker', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_query_blocker_currentdbname'), ['currentdbname'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_blocker_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_blocker_month_year'), ['month_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_blocker_query_hash'), ['query_hash'], unique=True)

    op.create_table('raw_query_deadlock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_hash', _S(), nullable=False),
    sa.Column('host', _S(), nullable=True),
    sa.Column('db_name', _S(), nullable=True),
    sa.Column('environment', _S(), nullable=False),
    sa.Column('month_year', _S(), nullable=True),
    sa.Column('event_time', _S(), nullable=True),
    sa.Column('deadlock_id', _S(), nullable=True),
    sa.Column('is_victim', sa.Integer(), nullable=True),
    sa.Column('lock_mode', _S(), nullable=True),
    sa.Column('wait_resource', _S(), nullable=True),
    sa.Column('wait_time_ms', sa.Integer(), nullable=True),
    sa.Column('transaction_name', _S(), nullable=True),
    sa.Column('app_host', _S(), nullable=True),
    sa.Column('sql_text', _S(), nullable=True),
    sa.Column('raw_xml', _S(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_query_deadlock', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_query_deadlock_db_name'), ['db_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_deadlock_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_deadlock_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_deadlock_month_year'), ['month_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_deadlock_query_hash'), ['query_hash'], unique=True)

    op.create_table('raw_query_slow_mongo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_hash', _S(), nullable=False),
    sa.Column('host', _S(), nullable=True),
    sa.Column('db_name', _S(), nullable=True),
    sa.Column('collection', _S(), nullable=True),
    sa.Column('environment', _S(), nullable=False),
    sa.Column('month_year', _S(), nullable=True),
    sa.Column('event_time', _S(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('plan_summary', _S(), nullable=True),
    sa.Column('op_type', _S(), nullable=True),
    sa.Column('remote_client', _S(), nullable=True),
    sa.Column('command_json', _S(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_query_slow_mongo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_query_slow_mongo_collection'), ['collection'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_slow_mongo_db_name'), ['db_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_slow_mongo_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_slow_mongo_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_slow_mongo_month_year'), ['month_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_slow_mongo_query_hash'), ['query_hash'], unique=True)

    op.create_table('raw_query_slow_sql',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_hash', _S(), nullable=False),
    sa.Column('host', _S(), nullable=True),
    sa.Column('db_name', _S(), nullable=True),
    sa.Column('environment', _S(), nullable=False),
    sa.Column('month_year', _S(), nullable=True),
    sa.Column('creation_time', _S(), nullable=True),
    sa.Column('last_execution_time', _S(), nullable=True),
    sa.Column('max_elapsed_time_s', sa.Float(), nullable=True),
    sa.Column('avg_elapsed_time_s', sa.Float(), nullable=True),
    sa.Column('total_elapsed_time_s', sa.Float(), nullable=True),
    sa.Column('total_worker_time_s', sa.Float(), nullable=True),
    sa.Column('avg_io', sa.Float(), nullable=True),
    sa.Column('avg_logical_reads', sa.Float(), nullable=True),
    sa.Column('avg_logical_writes', sa.Float(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('query_final', _S(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_query_slow_sql', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_query_slow_sql_db_name'), ['db_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_slow_sql_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_slow_sql_host'), ['host'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_slow_sql_month_year'), ['month_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_query_slow_sql_query_hash'), ['query_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('raw_query_slow_sql', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_sql_query_hash'))
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_sql_month_year'))
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_sql_host'))
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_sql_environment'))
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_sql_db_name'))

    op.drop_table('raw_query_slow_sql')
    with op.batch_alter_table('raw_query_slow_mongo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_mongo_query_hash'))
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_mongo_month_year'))
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_mongo_host'))
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_mongo_environment'))
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_mongo_db_name'))
        batch_op.drop_index(batch_op.f('ix_raw_query_slow_mongo_collection'))

    op.drop_table('raw_query_slow_mongo')
    with op.batch_alter_table('raw_query_deadlock', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_query_deadlock_query_hash'))
        batch_op.drop_index(batch_op.f('ix_raw_query_deadlock_month_year'))
        batch_op.drop_index(batch_op.f('ix_raw_query_deadlock_host'))
        batch_op.drop_index(batch_op.f('ix_raw_query_deadlock_environment'))
        batch_op.drop_index(batch_op.f('ix_raw_query_deadlock_db_name'))

    op.drop_table('raw_query_deadlock')
    with op.batch_alter_table('raw_query_blocker', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_query_blocker_query_hash'))
        batch_op.drop_index(batch_op.f('ix_raw_query_blocker_month_year'))
        batch_op.drop_index(batch_op.f('ix_raw_query_blocker_environment'))
        batch_op.drop_index(batch_op.f('ix_raw_query_blocker_currentdbname'))

    op.drop_table('raw_query_blocker')
    # ### end Alembic commands ###
