"""add user table

Revision ID: 6901e63c50d9
Revises: 9db879faabd3
Create Date: 2026-03-13 16:29:28.351279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6901e63c50d9'
down_revision: Union[str, Sequence[str], None] = '9db879faabd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pattern', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pattern_environment'))
        batch_op.drop_index(batch_op.f('ix_pattern_name'))
        batch_op.drop_index(batch_op.f('ix_pattern_pattern_tag'))
        batch_op.drop_index(batch_op.f('ix_pattern_severity'))
        batch_op.drop_index(batch_op.f('ix_pattern_source'))
        batch_op.drop_index(batch_op.f('ix_pattern_type'))

    op.drop_table('pattern')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pattern',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('pattern_tag', sa.VARCHAR(), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=8), nullable=False),
    sa.Column('example_query_hash', sa.VARCHAR(), nullable=True),
    sa.Column('source', sa.VARCHAR(length=7), nullable=True),
    sa.Column('environment', sa.VARCHAR(length=7), nullable=True),
    sa.Column('type', sa.VARCHAR(length=10), nullable=True),
    sa.Column('first_seen', sa.DATETIME(), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.Column('total_occurrences', sa.INTEGER(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pattern', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pattern_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_pattern_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_pattern_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_pattern_pattern_tag'), ['pattern_tag'], unique=False)
        batch_op.create_index(batch_op.f('ix_pattern_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_pattern_environment'), ['environment'], unique=False)

    # ### end Alembic commands ###
