"""initial_schema_raw_query_and_pattern

Revision ID: 9db879faabd3
Revises:
Create Date: 2026-03-03 17:05:09.233409

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9db879faabd3"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pattern",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("pattern_tag", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "severity", sa.Enum("critical", "warning", "info", name="severitytype"), nullable=False
        ),
        sa.Column("example_query_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sa.Enum("sql", "mongodb", name="sourcetype"), nullable=True),
        sa.Column(
            "environment", sa.Enum("prod", "sat", "unknown", name="environmenttype"), nullable=True
        ),
        sa.Column(
            "type",
            sa.Enum("slow_query", "blocker", "deadlock", "unknown", name="querytype"),
            nullable=True,
        ),
        sa.Column("first_seen", sa.DateTime(), nullable=True),
        sa.Column("last_seen", sa.DateTime(), nullable=True),
        sa.Column("total_occurrences", sa.Integer(), nullable=False),
        sa.Column("notes", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("pattern", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_pattern_environment"), ["environment"], unique=False)
        batch_op.create_index(batch_op.f("ix_pattern_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_pattern_pattern_tag"), ["pattern_tag"], unique=False)
        batch_op.create_index(batch_op.f("ix_pattern_severity"), ["severity"], unique=False)
        batch_op.create_index(batch_op.f("ix_pattern_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_pattern_type"), ["type"], unique=False)

    op.create_table(
        "raw_query",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("time", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("source", sa.Enum("sql", "mongodb", name="sourcetype"), nullable=False),
        sa.Column("host", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("db_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "environment", sa.Enum("prod", "sat", "unknown", name="environmenttype"), nullable=False
        ),
        sa.Column(
            "type",
            sa.Enum("slow_query", "blocker", "deadlock", "unknown", name="querytype"),
            nullable=False,
        ),
        sa.Column("query_details", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("month_year", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("first_seen", sa.DateTime(), nullable=False),
        sa.Column("last_seen", sa.DateTime(), nullable=False),
        sa.Column("pattern_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["pattern_id"],
            ["pattern.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("raw_query", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_raw_query_db_name"), ["db_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_query_environment"), ["environment"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_query_host"), ["host"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_query_month_year"), ["month_year"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_query_pattern_id"), ["pattern_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_query_query_hash"), ["query_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_raw_query_source"), ["source"], unique=False)
        batch_op.create_index(batch_op.f("ix_raw_query_type"), ["type"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_query", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_query_type"))
        batch_op.drop_index(batch_op.f("ix_raw_query_source"))
        batch_op.drop_index(batch_op.f("ix_raw_query_query_hash"))
        batch_op.drop_index(batch_op.f("ix_raw_query_pattern_id"))
        batch_op.drop_index(batch_op.f("ix_raw_query_month_year"))
        batch_op.drop_index(batch_op.f("ix_raw_query_host"))
        batch_op.drop_index(batch_op.f("ix_raw_query_environment"))
        batch_op.drop_index(batch_op.f("ix_raw_query_db_name"))

    op.drop_table("raw_query")
    with op.batch_alter_table("pattern", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_pattern_type"))
        batch_op.drop_index(batch_op.f("ix_pattern_source"))
        batch_op.drop_index(batch_op.f("ix_pattern_severity"))
        batch_op.drop_index(batch_op.f("ix_pattern_pattern_tag"))
        batch_op.drop_index(batch_op.f("ix_pattern_name"))
        batch_op.drop_index(batch_op.f("ix_pattern_environment"))

    op.drop_table("pattern")
    # ### end Alembic commands ###
